---
- name: Read and display encrypted file
  hosts: localhost
  vars_files:
    - secrets.txt # Hier muss der Name der verschlüsselten Datei angegeben werden
  tasks:
    - name: Display the content of the encrypted file
      debug:
        msg: "The secret password is: {{ secretPasswort }}"
